apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service-php
  labels:
    app: log-service-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service-php
  template:
    metadata:
      labels:
        app: log-service-php
    spec:
      containers:
        - name: log-service-php
          image: log-service-php:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1-php"
            - name: LOG_LEVEL
              value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: log-service-php
  labels:
    app: log-service-php
spec:
  type: LoadBalancer
  selector:
    app: log-service-php
  ports:
    - name: http
      port: 8080
      targetPort: 8080
