apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  labels:
    app: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: log-service
          image: log-service-with-otel:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "otel-enabled"
            - name: LOG_LEVEL
              value: "info"
            - name: DEPENDENCY_URL
              value: "http://echo-service:8080/info"
            - name: OTEL_SERVICE_NAME
              value: "log-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
  labels:
    app: log-service
spec:
  type: ClusterIP
  selector:
    app: log-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
