apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

# Patch: Scale down for dev (save resources)
patches:
  - target:
      kind: Deployment
      name: compute-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

# Patch: Lower resource requests for dev
  - target:
      kind: Deployment
      name: compute-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"

# Patch: ConfigMap for dev environment
  - path: config-patch.yaml
